# Generated by Django 4.0 on 2021-12-08 18:33

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth import get_user_model
from django.utils import timezone

CATEGORY_LIST = [
    'Games',
    'Clothes',
    'Food',
    'Textile'
]


def create_superuser(apps, schema_editor):
    superuser = get_user_model()(
        is_active=True,
        is_superuser=True,
        is_staff=True,
        username='admin',
        last_login=timezone.now(),
    )
    superuser.set_password('admin')
    superuser.save()


def add_default_categories(apps, schema_editor):
    mode_class = apps.get_model("share_place", "Category")
    for cat in CATEGORY_LIST:
        mode_class.objects.get_or_create(
            title=cat
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='share_place.category')),
            ],
        ),
        migrations.RunPython(add_default_categories),
        migrations.RunPython(create_superuser)
    ]
